include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/generated_plugin_registrant.dart"
    - "**/firebase_options.dart"
  errors:
    unnecessary_lambdas: ignore
    invalid_annotation_target: ignore
    missing_required_param: error
    missing_return: error
    todo: ignore
    parameter_assignments: error

linter:
  rules:
    - prefer_constructors_over_static_methods
    - prefer_relative_imports
    - prefer_const_declarations
    - prefer_const_constructors
    - prefer_single_quotes
    - require_trailing_commas
    - sort_constructors_first
    - tighten_type_of_initializing_formals
    - prefer_final_locals
    - prefer_final_in_for_each
    - unnecessary_lambdas
    - unnecessary_library_directive
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - use_string_buffers
    - use_to_and_as_if_applicable
    - parameter_assignments
    - avoid_slow_async_io
